//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteValidacao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int cli_id { get; set; }
        public string nome { get; set; }
        public int idade { get; set; }
        public string email { get; set; }
        public double preco { get; set; }
    }
}
